### ISSUE TITLE
big number modular arithmetics

### ISSUE THREAD

**Issue by kunerd** [rust-lang/num#103]
For a research project I am working on, we implement different privacy preserving data mining algorithms in Java. Now, that some of the algorithms are working, I thought about porting them into a rust library - for fun and to learn more about rust.
After I started I realised a lag of fundamental big number arithmetic functions like `mod_pow` and `mod_inverse`.  Also, at the moment there is no way to generate probably primes. In Java these things are implemented in the `BigInteger` class.

My question now is, are there any plans to add these functions to rust's `BigInt` or would it be better to create a own library for them?

**Comment by kunerd** [comment]
current state of my implementation:
* `mod_pow`: Implementation of LR-k-ary algorithm as described in the "[Handbook of Applied Cryptography](http://cacr.uwaterloo.ca/hac/about/chap14.pdf), 14.82".
* `mod_inverse`: Implementation of "Extended Euclidean Algorithm" as described by Knuth

**Comment by allan-simon** [comment]
+1 for  mod_pow

**Comment by allan-simon** [comment]
@kunerd  , if you propose a PR, it will get more chance to get accepted, especially if you've already implemented it

**Comment by kunerd** [comment]
My current solution adds a 'trait' for each of the two functions, but I don't know, if this is a good practice. It will be my first PR and I think I need some help.

**Comment by kunerd** [comment]
acrichton and I decided to create separate crates for the functionalities described above. (see here: https://github.com/rust-lang/num/pull/104)
My newly created repository for `mod_pow` can be found here:
https://github.com/kunerd/mod_pow
