### ISSUE TITLE
Need ways to convert BigUint into bytes

### ISSUE THREAD

**Issue by divius** [rust-lang/num#5]
Hi! I'm implementing BitTorrent DHT [1] and I'm using BigUint for storing 160-bit ID. On-wire format requires ID to be encoded as 20 bytes in network byte order (see "Contact Encoding" section). It would be nice to have the following methods for BigUint (and maybe also BigInt, though not sure here):

 to_bytes_be(&self) -> Vec<u8>
 to_bytes_le(&self) -> Vec<u8>
 to_bytes(&self) -> Vec<u8>   // platform default representation, do we know it from inside Rust?

I can work on the implementation, if core team is ok with this feature.

**Comment by gsingh93** [comment]
This was fixed. This issue should be closed.

**Comment by huonw** [comment]
Thanks
