### ISSUE TITLE
Consider splitting into smaller crates

### ISSUE THREAD

**Issue by felixc** [rust-lang/num#63]
Given that the data types in here are relatively “fundamental” (some having even been part of the standard library in the past), they're likely to be used in a lot of places. It would therefore be nice to have more fine-grained control over these dependencies, to minimize unnecessary bloat. In particular, `rational`, `bigint`, and `complex` seem like reasonably separate concepts/libraries.

For example, I was just now surprised to see that adding a simple `Rational` to my code pulled in dependencies relating to logging, serialization, and random numbers. I want to use a common type that consumers of my library are likely to be able to use without converting from my own `Rational` type, but I also don't want my code to transitively pull in a lot of stuff for its users.

**Comment by bluss** [comment]
I'd like to have the traits separate, Num and those similar.
