### ISSUE TITLE
Will `std::num::Float` be moved here?

### ISSUE THREAD

**Issue by bvssvni** [rust-lang/num#74]
See https://github.com/PistonDevelopers/piston/issues/864

We use the `Float` for generics in some piston libraries, and wonder what's the plan of replacing the trait.

**Comment by alexcrichton** [comment]
Yes I believe the current plan is to move the generic traits into this crate for the time being.

cc @aturon

**Comment by aturon** [comment]
See https://github.com/rust-lang/num/pull/75!
